# Generated by Django 5.0 on 2023-12-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=25, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.BooleanField(unique=True)),
                ('tipo', models.CharField(max_length=15, unique=True)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('num_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.FloatField()),
                ('id_asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id_organizador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=25, unique=True)),
                ('constrasenia', models.CharField(max_length=15)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id_boleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='party_management.ordencompra')),
                ('num_orden', models.IntegerField()),
                ('cantidad_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('limite', models.IntegerField()),
                ('id_organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Vende',
            fields=[
                ('id_boleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vende_boleto', serialize=False, to='party_management.organizador')),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('ice', models.FloatField()),
                ('id_organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vende_organizador', to='party_management.organizador')),
            ],
        ),
    ]
