# Generated by Django 4.2.7 on 2024-01-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
