# Generated by Django 5.0 on 2023-12-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizador',
            old_name='constrasenia',
            new_name='contrasenia',
        ),
    ]
