# Generated by Django 5.0.1 on 2024-01-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
