# Generated by Django 4.2.7 on 2024-01-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vende',
            name='precio_actual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
