# Generated by Django 4.2.7 on 2024-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gasto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
