# Generated by Django 4.2.7 on 2024-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0002_evento_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(),
        ),
    ]
