# Generated by Django 5.0 on 2023-12-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0002_alter_asistente_options_alter_asistente_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizador',
            old_name='constrasenia',
            new_name='contrasenia',
        ),
    ]
