# Generated by Django 4.2.7 on 2024-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0002_vende_precio_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
