# Generated by Django 5.0 on 2023-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0003_rename_constrasenia_organizador_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
