# Generated by Django 5.0 on 2023-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0003_organizador_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
