# Generated by Django 4.2.7 on 2024-01-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0003_alter_ordencompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vende',
            name='ice',
        ),
    ]
