# Generated by Django 5.0 on 2023-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0004_organizador_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(),
        ),
    ]
