# Generated by Django 5.0 on 2023-12-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0004_organizador_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vende',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vende_boleto', serialize=False, to='party_management.boleto'),
        ),
    ]
