# Generated by Django 4.2.7 on 2024-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0004_remove_vende_ice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vende',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
