# Generated by Django 5.0 on 2024-01-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0004_organizador_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='boleto',
            name='id_evento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='party_management.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='tipoBoleto',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contiene',
            name='boleto_cdg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vende',
            name='precio_actual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vende',
            name='stock_actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vende',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vende_boleto', serialize=False, to='party_management.boleto'),
        ),
    ]
