# Generated by Django 5.0 on 2023-12-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0004_evento_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(),
        ),
    ]
