# Generated by Django 5.0 on 2023-12-31 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_boleto_stock_alter_evento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contiene',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='party_management.boleto'),
        ),
        migrations.AlterField(
            model_name='contiene',
            name='num_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.ordencompra'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='vende',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vende_boleto', serialize=False, to='party_management.boleto'),
        ),
    ]
