# Generated by Django 5.0 on 2023-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_vende_id_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
