# Generated by Django 4.2.7 on 2023-12-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_boleto_stock_alter_evento_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='tipo',
            new_name='tipoBoleto',
        ),
    ]
