# Generated by Django 5.0 on 2023-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_evento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
