# Generated by Django 4.2.7 on 2024-01-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_vende_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vende',
            name='iva',
            field=models.FloatField(),
        ),
    ]
