# Generated by Django 5.0 on 2023-12-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0006_alter_evento_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='image',
        ),
    ]
