# Generated by Django 4.2.7 on 2024-01-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0006_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre_evento',
            field=models.CharField(max_length=50),
        ),
    ]
