# Generated by Django 5.0 on 2023-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0006_alter_boleto_stock_alter_boleto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(),
        ),
    ]
