# Generated by Django 4.2.7 on 2023-12-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0006_rename_tipo_boleto_tipoboleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='tipoBoleto',
            field=models.CharField(max_length=15),
        ),
    ]
