# Generated by Django 5.0 on 2024-01-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0002_evento_imagen'),
        ('party_management', '0006_alter_boleto_precio_alter_vende_iva'),
    ]

    operations = [
    ]
