# Generated by Django 5.0 on 2023-12-31 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0007_alter_boleto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contiene',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='party_management.boleto'),
        ),
    ]
