# Generated by Django 4.2.7 on 2023-12-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0007_alter_boleto_stock_alter_boleto_tipoboleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vende',
            name='descuento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vende',
            name='ice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vende',
            name='iva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
