# Generated by Django 4.2.7 on 2023-12-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0008_alter_vende_descuento_alter_vende_ice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vende',
            name='descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vende',
            name='ice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vende',
            name='iva',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
