# Generated by Django 5.0 on 2023-12-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0008_evento_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='image',
        ),
    ]
