# Generated by Django 5.0 on 2023-12-31 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0008_alter_contiene_id_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contiene',
            name='num_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.ordencompra'),
        ),
    ]
