# Generated by Django 5.0 on 2023-12-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0009_remove_evento_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(unique=True),
        ),
    ]
