# Generated by Django 5.0 on 2023-12-31 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_alter_boleto_stock_alter_evento_hora'),
        ('party_management', '0009_alter_contiene_num_orden'),
    ]

    operations = [
    ]
