# Generated by Django 4.2.7 on 2023-12-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0009_alter_vende_descuento_alter_vende_ice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='tipoBoleto',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='contiene',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='party_management.boleto'),
        ),
        migrations.AlterField(
            model_name='contiene',
            name='num_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_management.ordencompra'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='vende',
            name='id_boleto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vende_boleto', serialize=False, to='party_management.boleto'),
        ),
    ]
