# Generated by Django 5.0 on 2023-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0010_merge_20231230_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
