# Generated by Django 4.2.7 on 2023-12-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0010_rename_tipoboleto_boleto_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='tipo',
            new_name='tipoBoleto',
        ),
    ]
