# Generated by Django 5.0 on 2024-01-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0011_alter_boleto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vende',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
    ]
