# Generated by Django 5.0 on 2024-01-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0005_remove_boleto_tipo_boleto_id_evento_and_more'),
        ('party_management', '0007_alter_evento_hora'),
        ('party_management', '0011_alter_boleto_stock'),
    ]

    operations = [
    ]
