# Generated by Django 5.0 on 2024-01-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0012_vende_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contiene',
            name='boleto_cdg',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
