# Generated by Django 4.2.7 on 2023-12-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0012_evento_id_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id_boleto',
        ),
    ]
