# Generated by Django 4.2.7 on 2023-12-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0013_remove_evento_id_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='id_boleto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party_management.boleto'),
            preserve_default=False,
        ),
    ]
