# Generated by Django 4.2.7 on 2023-12-31 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0014_evento_id_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id_boleto',
        ),
        migrations.AddField(
            model_name='boleto',
            name='id_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party_management.evento'),
            preserve_default=False,
        ),
    ]
