# Generated by Django 4.2.7 on 2023-12-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0015_remove_evento_id_boleto_boleto_id_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
