# Generated by Django 4.2.7 on 2023-12-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0016_evento_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
