# Generated by Django 4.2.7 on 2023-12-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0017_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
