# Generated by Django 4.2.7 on 2024-01-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_management', '0018_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='vende',
            name='stock_actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
